#!/bin/sh
#

[ -r /etc/lsb-release ] && . /etc/lsb-release

printf "\n"
printf "\e[1;34m
    __     _                             __ __  _  __     ______
   / /    (_)____   __  __ _  __        / //_/ (_)/ /_   / ____/____   _____ ___ 
  / /    / // __ \ / / / /| |/_/______ / ,<   / // __/  / /    / __ \ / ___// _ \\
 / /___ / // / / // /_/ /_>  < /_____// /| | / // /_   / /___ / /_/ // /   /  __/
/_____//_//_/ /_/ \__,_//_/|_|       /_/ |_|/_/ \__/   \____/ \____//_/    \___/
\e[0m\n"

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
printf "\n"
printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
