#!/bin/sh
#
#    10-help-text - print the help text associated with the distro

printf "\n"
printf " * Documentation:  http://doc.linuxkit.com\n"
printf " * Management:     http://www.linuxkit.com\n"

if [ -e /etc/build-release ];then 
    cat /etc/build-release 
fi
